version: '3.8'

services:
  # PostgreSQL 資料庫
  db:
    image: postgres:16-alpine
    container_name: accounting_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-accounting}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Flask 應用
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: accounting_app
    environment:
      # 資料庫連線（使用 Docker 內部網路）
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-accounting}

      # Flask 密鑰
      SECRET_KEY: ${SECRET_KEY:-change-me-in-production}
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
    driver: local
